### PR TITLE
Add tabular_learner section

### PR DESCRIPTION
**Pull request by TheooJ**
Add a `tabular_learner` example on the landing page

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Awesome!

A few comments:
1. It seems to me that the centering of the "Less data wrangling..." is broken. Could you have a look at how to recenter this
2. We need a bit more vertical space below the "Less data wrangling"...
3. Optional: it would have been really cool to have an html view of the 3 first lines of the dataframe instead of the iloc[0]. A bit like on https://twitter.com/skrub_data/status/1808082182512017478

**Comment by GaelVaroquaux** [comment]
One more thing: I would like the term "messy dataframe" or "wrangling" to appear in the short sentence. How about:

`tabular_learner`: one function to create a tabular-learning pipeline that wrangles complex dataframes.

Or

`tabular_learner`: easily create tabular-learning pipelines that wrangle complex dataframes.

**Review by jeromedockes — APPROVED** [review]
LGTM, thanks a lot @TheooJ ! to be continued...

**Comment by GaelVaroquaux** [comment]
Excellent!!

**Pull request merged**
