### PR TITLE
Add summary stats panel in report

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Can you please do a trivial change (eg add an empty line) to the getting started example, so that our CI renders it, and we can check how the table report looks like via the rendered docs?

Thanks!

**Comment by jeromedockes** [comment]
> Can you please do a trivial change (eg add an empty line) to the getting started example, so that our CI renders it, and we can check how the table report looks like via the rendered docs?
>
> Thanks!

yep, I did it on the previous one but forgot to redo it after the last
change.

FYI git commit has the `--allow-empty` option in cases where you want to
push a commit to trigger the CI but don't have any change to make

**Comment by GaelVaroquaux** [comment]
> FYI git commit has the `--allow-empty` option in cases where you want to push a commit to trigger the CI but don't have any change to make

Indeed. But I think our CI detects that the example has not been changed and does not run, to decrease computation costs.

**Comment by jeromedockes** [comment]
> Indeed. But I think our CI detects that the example has not been changed and does not run, to decrease computation costs.

ah yes that's a good point, [ci-build] runs all the examples

**Comment by GaelVaroquaux** [comment]
> ah yes that's a good point, [ci-build] runs all the examples

But only once. And what we would like is that this specific example is rerun for each push, to facilitate looking at the TableReport.

**Review by Vincent-Maladiere — APPROVED** [review]
Very useful, LGTM!

**Review by GaelVaroquaux — APPROVED** [review]
Excellent!

This looks good to merge to me

**Comment by GaelVaroquaux** [comment]
Two approvals, merging

**Pull request merged**
