### PR TITLE
[MRG] fix failing coverage report upload

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by Vincent-Maladiere** [comment]
Is codecov supposed to be displayed on the CI of this PR?

**Comment by jeromedockes** [comment]
> Is codecov supposed to be displayed on the CI of this PR? 

Not yet but it will once the problem is fixed :)

**Comment by jeromedockes** [comment]
@Vincent-Maladiere  should be ok now

**Review by Vincent-Maladiere — APPROVED** [review]
LGTM!

**Pull request merged**
