### PR TITLE
removed filter warnings and fuzzy join() experimental warning

### PR DESCRIPTION
**Pull request by dcor01**
Working towards #766

I have removed the warning thrown everytime fuzzy_join() is called. I have also got rid of the warnings.filterwarnings("ignore") in example 4. 

I got rid of the other changes

### CODE REVIEW

**Review by jeromedockes — DISMISSED** [review]
thank you!

**Comment by jeromedockes** [comment]
At the beginning of the script could you replace
```python
y = df3[["Happiness score"]]
```

with

```python
y = df3["Happiness score"]
```

Otherwise we get a DataConversionWarning later on as you can see in the [rendered docs](https://output.circle-artifacts.com/output/job/5e79d4d8-1231-49de-8985-c81a1d56488b/artifacts/0/doc/auto_examples/04_fuzzy_joining.html#sphx-glr-auto-examples-04-fuzzy-joining-py)

Thank you!

**Comment by dcor01** [comment]
Thanks Jerome - I have made the change

**Review by jeromedockes — APPROVED** [review]
great, thanks a lot! this is a small change so I don't think we need another review; I'll merge once the CI tests finish :)

**Pull request merged**
