### PR TITLE
Adding gradient bandeau and remove right secondary side bar

### PR DESCRIPTION
**Pull request by Vincent-Maladiere**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Cool!!

It seems that the white on the background of the schematic is back. 

In addition, the contrasts of the font in the banner is a bit small in black background because the font is white. Maybe we could change the definition of colors of the background using transparency, so that  when the background is white they match the color for scikit-learn, but when the background is black they are darker (thanks to transparency)

**Comment by GaelVaroquaux** [comment]
Also, we have a failure in the build. Looks like a failure in the examples. I'm not sure how we got there.

**Comment by jovan-stojanovic** [comment]
Looks great! 
It seems an error slipped in with #514, I corrected it #591. Just merge with main @Vincent-Maladiere and it will become green

**Comment by Vincent-Maladiere** [comment]
Closing for https://github.com/skrub-data/skrub/pull/589

**Comment by GaelVaroquaux** [comment]
Reopened: my PR was a PR to your PR (yes, very confusing, sorry)

**Comment by GaelVaroquaux** [comment]
Will merge this PR once it is green. However, should we not remove the index.rst right now?

**Comment by GaelVaroquaux** [comment]
Darn removing index.rst messed up our navbar.

We should add it back, but mostly empty, as it is unused.

**Comment by GaelVaroquaux** [comment]
LGTM (looks gorgious to me). Merging :heart: :heart: :heart:

**Pull request merged**
