### PR TITLE
REL bump version to 0.2.0 + cherry-pick doc updates

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Can you wait 1hr, I have a PR for the landing page

**Comment by jeromedockes** [comment]
> Can you wait 1hr, I have a PR for the landing page

sure, no problem

**Comment by GaelVaroquaux** [comment]
OK, https://github.com/skrub-data/skrub/pull/987 is what I had in mind. It's ready for review

**Review by GaelVaroquaux — APPROVED** [review]
LGTM (though the diff is polluted by my PR :D )

**Pull request merged**
