### PR TITLE
Easier copying of TableReport table cells

### PR DESCRIPTION
**Pull request by jeromedockes**
A few small adjustments after euroscipy discussions
Will add a few more soon

### CODE REVIEW

**Review by Vincent-Maladiere — COMMENTED** [review]
Hello Jérome, unfortunately, I still can't copy-past with a single click on Chrome and Chrome + Arc. I need to double-click to copy. I will try on Firefox.

**Comment by Vincent-Maladiere** [comment]
Yes, so I works fine on Firefox but not on Chrome.

**Comment by jeromedockes** [comment]
cool thanks for checking!

**Comment by jeromedockes** [comment]
I can't reproduce the issue on Chrome on Linux

**Comment by Vincent-Maladiere** [comment]
Ok, so unless there is an easy fix, I guess we can skip this feature for Chrome on MacOS for now?

**Comment by jeromedockes** [comment]
I'm guessing that's a significant proportion of users so I'd like to investigate a bit more (also I need to check the failing test)

**Comment by jeromedockes** [comment]
ok @Vincent-Maladiere this one is ready now

**Review by Vincent-Maladiere — APPROVED** [review]
It works fine on Chrome for MacOS!

**Pull request merged**
