### PR TITLE
REL skrub 0.1.1

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by jeromedockes** [comment]
(note the failure is expected, this PR doesn't mention a PR number in the changes made to the changelog)

**Comment by glemaitre** [comment]
You can add the label and the error is ignore ;)

**Review by glemaitre — APPROVED** [review]
LGTM to me. We can release this one quickly.

**Comment by jeromedockes** [comment]
thanks @glemaitre !

**Pull request merged**
