### PR TITLE
[MAINT] Replace Sphinx Gallery dev by stable

### PR DESCRIPTION
**Pull request by Vincent-Maladiere**
Follow-up on https://github.com/skrub-data/skrub/pull/703 since the bug seems to have been addressed.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Related: can we set up the sphinx-gallery recommender system please?

Talk to Arturo if you need help / advice.

**Comment by Vincent-Maladiere** [comment]
In this PR or in a next one?

**Comment by GaelVaroquaux** [comment]
> In this PR or in a next one?

Whatever you feel is best

**Review by jeromedockes — APPROVED** [review]

**Comment by jeromedockes** [comment]
> In this PR or in a next one?

let's do it in another one as it seems a bit orthogonal

**Pull request merged**
