### PR TITLE
MAINT  add support for Python 3.9

### LINKED ISSUE #815: support python 3.8 & 3.9
Why is the oldest python version supported by skrub 3.10?
end of support for 3.8 is only [scheduled](https://www.python.org/downloads/) for October 2024 so unless there is a compelling reason not to I think skrub should work on python 3.8
I see that would require changing some of the type annotations, are there other reasons why we chose 3.10?

### PR DESCRIPTION
**Pull request by jeromedockes**
closes #868, closes #815

### CODE REVIEW

**Comment by jeromedockes** [comment]
the macos + python 3.8 fails to install pre-commit; not really related to skrub. As  #928 will redo the CI configuration I won't edit it here

**Comment by jeromedockes** [comment]
the latest scikit-learn release only supports 3.9 so I wonder if we should set that as our minimum supported version? OTOH we support older scikit-learn versions that work with python 3.8

**Review by glemaitre — APPROVED** [review]
LTGM. Not really sure why we have those "required" GHA.

**Comment by jeromedockes** [comment]
> LTGM. Not really sure why we have those "required" GHA.

ah I see what happened -- we require all tests to pass in the CI before allowing to merge a PR. That  includes the py3.10 tests, but they don't exist anymore because i replaced 3.10 with 3.9 (the matrix of os/python/dependencies combinations is already huge) I guess I'll just add 3.10 back; anyway this is temporary because your pixi PR will redo the configuration

**Pull request merged**
