### PR TITLE
tablereport display details

### PR DESCRIPTION
**Pull request by jeromedockes**
a small detail so it is aligned when wrapping

### CODE REVIEW

**Comment by Vincent-Maladiere** [comment]
It's hard to see what changes, can you provide screenshots?

**Comment by jeromedockes** [comment]
sure, it's really a detail. it is just about alignment of the dropdown when there is a very narrow display

before:

screenshot_2024-09-12T13:52:34+02:00

after:

screenshot_2024-09-12T13:54:53+02:00

**Comment by jeromedockes** [comment]
the change on the tab margin is just that on a high-resolution large screen at some zoom levels in jupyter notebooks only I could see a very thin gray line between the selected tab and its panel, but I can't seem to reproduce it on my laptop to provide a screenshot

**Comment by Vincent-Maladiere** [comment]
Hey @jeromedockes, is this PR ready for review?

**Comment by jeromedockes** [comment]
> Hey @jeromedockes, is this PR ready for review?

yes, thank you!

**Review by TheooJ — APPROVED** [review]
Thanks !

**Comment by Vincent-Maladiere** [comment]
Well, I would have appreciated reviewing it before merging.

**Pull request merged**
