### PR TITLE
TST polars support for deduplicate

### PR DESCRIPTION
**Pull request by TheooJ**
Closing issue #789  

Checking if `deduplicate` works with polars input in `test_deduplicate.py`

I propose to catch any exceptions, let me know if you want to be more specific

### CODE REVIEW

**Comment by Vincent-Maladiere** [comment]
@TheooJ you have to create a specific issue for the meta-issue you're addressing.
- This PR should mention the sub-issue only (you can edit your message)
- The sub-issue should mention the meta-issue only

Otherwise, the meta-issue will be automatically closed when we merge a single PR that refers to it.

**Comment by TheooJ** [comment]
Thanks, done.

**Review by Vincent-Maladiere — CHANGES_REQUESTED** [review]
Thanks for this PR. Good job using utils from `test_polars`! In addition to checking errors, we also want to check the results. In that sense, check that identical Pandas and Polars series inputs return the same output.

If the function you are testing already works fine with Polars, you don't need to catch a potential error. However, if this function doesn't work with Polars yet, we need to:
1. Add it to a list of functions that don't support Polars yet (create one in `test_polars.py`)
2. Use `pytest.mark.xfail` if the function you are testing belongs to the list. This will skip the test by displaying a soft fail (meaning: we acknowledge that this is failing, but this needs to be fixed). [Example in scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/preprocessing/tests/test_polynomial.py#L1215). Note that scikit-learn uses a more complex scheme for xfailing tests by using `_xfail_checks` tags in estimators. We can keep it simple for now and use a list, without using tags.

**Comment by TheooJ** [comment]
I've compared pandas and polars outputs in the same test function. If polars is missing, the test will be skipped. If the function either returns an error or if the pandas and outputs don't match, the test will xfail.

Let me know what you think

**Comment by TheooJ** [comment]
As discussed, I've removed the xfail completely if the polars test is successful.

If the test was failing, I would add 

```
# in test_polars
XFAIL_POLARS = ["deduplicate"]
```

```
# in test_deduplicate
from test_polars import XFAIL_POLARS

@pytest.mark.xfail("deduplicate" in XFAIL_POLARS, reason=Polars not supported for deduplicate yet.")
@pytest.mark.skipif(not POLARS_SETUP, reason=POLARS_MISSING_MSG)
def test_polars_input():
    [...]
```

**Review by Vincent-Maladiere — APPROVED** [review]
Hey @TheooJ, thank you for this PR! LGTM

**Pull request closed without merging**
