### PR TITLE
Add `doc/sg_execution_times.rst` to `.gitignore`

### PR DESCRIPTION
**Pull request by Tialo**
Resolves https://github.com/skrub-data/skrub/issues/782

### CODE REVIEW

**Review by Vincent-Maladiere — APPROVED** [review]
Thanks @Tialo, LGTM. Fun fact: this feature has been added to sphinx after an issue from @GaelVaroquaux https://github.com/sphinx-gallery/sphinx-gallery/pull/348 :)

**Comment by GaelVaroquaux** [comment]
> Fun fact: this feature has been added to sphinx after an issue from @GaelVaroquaux https://github.com/sphinx-gallery/sphinx-gallery/pull/348 :)

The ecosystem works! It's so beautiful to see! Thanks @Tialo

**Review by GaelVaroquaux — APPROVED** [review]
LGTM, thanks

**Comment by Tialo** [comment]
Wow! That's cool feature btw

**Pull request merged**
