### PR TITLE
base sizes in report on font size of parent element

### PR DESCRIPTION
**Pull request by jeromedockes**
also the tables are compressed a bit more

### CODE REVIEW

**Review by Vincent-Maladiere — APPROVED** [review]
Looks good!

**Comment by Vincent-Maladiere** [comment]
Here's how it looks on VSCode!

Screenshot 2024-10-02 at 10 09 18

**Comment by jeromedockes** [comment]
> Here's how it looks on VSCode!

cool thanks a lot for checking!

**Comment by jeromedockes** [comment]
thanks for the review @Vincent-Maladiere , merging

**Comment by GaelVaroquaux** [comment]
Great!! This is a big deal

I think that this warrants a small line in the changelog, as it impacts users (positively)

**Comment by jeromedockes** [comment]
> I think that this warrants a small line in the changelog, as it impacts users (positively)

Oops I forgot the changelog I'll do it in another one

**Pull request merged**
