### PR TITLE
[ENH] Drop numpy array input support

### PR DESCRIPTION
**Pull request by Vincent-Maladiere**
**Reference**
Addresses https://github.com/skrub-data/skrub/issues/830
Follows-up on https://github.com/skrub-data/skrub/pull/819 (after #819 is merged, the differences of this PR will reduce significantly)

**What does this PR implement**
Raise an error when the input `X` doesn't have an `__dataframe__` attribute (supported from Pandas version 1.5.3, our minimum supported version).

### CODE REVIEW

**Comment by jeromedockes** [comment]
if we don't have time to merge this before the release maybe we should at least remove mentions of ndarrays from the tablevectorizer docstring

**Comment by Vincent-Maladiere** [comment]
I'll create a PR for that today, thanks

**Comment by Vincent-Maladiere** [comment]
Nevermind, let's release first. We'll deal with this will the two follow-up PRs for TableVectorizer.

**Comment by TheooJ** [comment]
Closing as it was done in #902 with `CheckInputDataFrame`

**Pull request closed without merging**
