### PR TITLE
Faster example 07_multiple_key_join

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
- Fixes rst
- Makes 07_multiple_key_join faster (addresses  #729 )

### CODE REVIEW

**Review by Vincent-Maladiere — APPROVED** [review]

**Comment by GaelVaroquaux** [comment]
The exemple now takes 11mn. It's still long, but better. I think that we should accept the loss in prediction accuracy.

**Comment by Vincent-Maladiere** [comment]
What's taking so long in this example? Is this the quadratic time for nearest neighbors?

**Comment by GaelVaroquaux** [comment]
> What's taking so long in this example? Is this the quadratic time for nearest neighbors?

Yes, I think so. I hope that when we have the InterpJoin this will be much faster.

**Review by jovan-stojanovic — APPROVED** [review]
LGTM. Actually it took 40min with 50 000 before #680 was merged so this is much better

**Pull request merged**
